services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node

  node:
    build: ./node
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    working_dir: /usr/src/app
    command: node index.js
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/mysql_data:/var/lib/mysql
    tty: true


volumes:
  mysql_data:
